"""Obsidian vault integration for note-taking."""
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from app.config import get_settings
from app.services.gemini import get_gemini

logger = logging.getLogger(__name__)


class ObsidianService:
    """Service for saving notes to Obsidian vault."""

    def __init__(self):
        settings = get_settings()
        self.vault_path = settings.obsidian_vault_path
        self.enabled = self.vault_path is not None

        if self.enabled:
            logger.info(f"Obsidian integration enabled: {self.vault_path}")
        else:
            logger.info("Obsidian integration disabled (no vault path configured)")

    async def save_note(self, content: str, title: Optional[str] = None) -> dict:
        """
        Save a note to Obsidian vault.

        Args:
            content: The note content
            title: Optional title (will be generated by Gemini if not provided)

        Returns:
            dict with 'title' and 'filename'

        Raises:
            ValueError: If Obsidian integration is not enabled
            Exception: If note saving fails
        """
        if not self.enabled:
            raise ValueError("Obsidian integration is not enabled. Set OBSIDIAN_VAULT_PATH in .env")

        # Generate title and tags using Gemini if title not provided
        if not title:
            gemini = get_gemini()
            prompt = f"""Analyze this note content and generate:
1. A clean, concise title (3-8 words, no special characters except hyphens)
2. 2-3 relevant tags (lowercase, single words)

Note content:
{content[:500]}

Respond in this exact format:
TITLE:
[title here]

TAGS:
[tag1, tag2, tag3]"""

            response = await gemini.chat(prompt)
            parsed = self._parse_gemini_response(response)
            title = parsed["title"]
            tags = parsed["tags"]
        else:
            tags = ["note", "brain2"]

        # Create filename
        date_str = datetime.now().strftime("%Y-%m-%d")
        safe_title = self._sanitize_filename(title)
        filename = f"{date_str}_{safe_title}.md"

        # Ensure directory exists
        notes_dir = Path(self.vault_path) / "Brain2" / "Notes"
        notes_dir.mkdir(parents=True, exist_ok=True)

        # Create file path
        file_path = notes_dir / filename

        # Build frontmatter
        frontmatter = f"""---
date: {date_str}
tags: [{', '.join(tags)}]
source: brain2-telegram
---

# {title}

{content}
"""

        # Write file
        try:
            file_path.write_text(frontmatter, encoding="utf-8")
            logger.info(f"Saved note to Obsidian: {file_path}")
            return {
                "title": title,
                "filename": filename,
                "path": str(file_path)
            }
        except Exception as e:
            logger.error(f"Failed to save note to Obsidian: {e}")
            raise

    def _parse_gemini_response(self, response: str) -> dict:
        """Parse Gemini response for title and tags."""
        result = {
            "title": "Untitled Note",
            "tags": ["note", "brain2"]
        }

        lines = response.strip().split("\n")
        current_section = None

        for line in lines:
            line = line.strip()
            if line.startswith("TITLE:"):
                current_section = "title"
            elif line.startswith("TAGS:"):
                current_section = "tags"
            elif current_section == "title" and line:
                result["title"] = line
                current_section = None
            elif current_section == "tags" and line:
                # Parse tags (handle both comma-separated and bracket format)
                tags_str = line.strip("[]")
                tags = [t.strip().lower() for t in tags_str.split(",") if t.strip()]
                if tags:
                    result["tags"] = tags
                current_section = None

        return result

    def _sanitize_filename(self, title: str) -> str:
        """Convert title to safe filename."""
        # Replace spaces with hyphens
        safe = title.lower().replace(" ", "-")
        # Remove special characters except hyphens
        safe = "".join(c for c in safe if c.isalnum() or c == "-")
        # Remove consecutive hyphens
        while "--" in safe:
            safe = safe.replace("--", "-")
        # Trim hyphens from start/end
        safe = safe.strip("-")
        # Limit length
        return safe[:100]


# Singleton instance
_obsidian_instance: Optional[ObsidianService] = None


def get_obsidian() -> ObsidianService:
    """Get or create the singleton ObsidianService instance."""
    global _obsidian_instance
    if _obsidian_instance is None:
        _obsidian_instance = ObsidianService()
    return _obsidian_instance
